{% set version = "3.4.2" %}

package:
  name: hickle
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/h/hickle/hickle-{{ version }}.tar.gz
  sha256: 50945499b4acb5c333eca98ab64a61848eee62c10c6efed135bc2a60cbc62cce

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
    - pytest-cov
  run:
    - python
    - numpy
    - h5py

test:
  requires:
    - pytest
  imports:
    - hickle

about:
  home: http://github.com/telegraphic/hickle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A HDF5-based python pickle replacement for dumping and loading python variables to file.'

  description: |
    hickle is a neat, quick way of dumping python variables to HDF5 files that can be read 
    in most programming languages. Hickle is fast, and allows for transparent 
    compression of your data (LZF / GZIP). Hickle is built upon h5py, and can be used as a
    drop-in replacement for pickle/cPickle.
  doc_url: http://github.com/telegraphic/hickle/README.md
  dev_url: https://github.com/telegraphic/hickle

extra:
  recipe-maintainers:
    - telegraphic
